version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cinema_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
